name = "PropDicts"
uuid = "4dc08600-4268-439e-8673-d706fafbb426"
version = "0.2.5"

[deps]
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[compat]
Functors = "0.3, 0.4"
JSON = "0.21"
julia = "1.6"
